FROM nginx

COPY index.html /usr/share/nginx/html/sunflower/  
COPY style.css /usr/share/nginx/html/sunflower/
COPY /pkg /usr/share/nginx/html/sunflower/pkg
COPY assets /usr/share/nginx/html/sunflower/assets